FROM node:18-alpine

ENV NODE_ENV development
ENV NEXT_TELEMETRY_DISABLED 1

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --include=dev
COPY . .

EXPOSE 3000
ENV PORT 3000

CMD ["npm", "run", "dev"]
