FROM node:18-alpine

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --include=dev
COPY . .

EXPOSE 3000
ARG PORT=3000
ENV PORT=${PORT}

CMD ["npm", "run", "dev"]
