version: "3.8"
services:
  ns_postgres_dev:
    container_name: ns-postgres-dev
    image: postgres:12.0-alpine
    profiles: [development]
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ns_data_dev:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - ns_net

  ns_strapi_dev:
    container_name: ns-strapi-dev
    image: nextstory-strapi-dev:latest
    profiles: [development]
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ns_postgres_dev
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/package-lock.json:/opt/package-lock.json
      - ./backend/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - ns_net
    depends_on:
      - ns_postgres_dev

  ns_nextjs_dev:
    container_name: ns-nextjs-dev
    image: nextstory-nextjs-dev:latest
    profiles: [development]
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      # We don't need to pass args here because everything is dynamically
      # rendered in the development environment.
    env_file:
      # This doesn't seem to work at all, but is here just in case.
      # Use --env-file flag instead when running the command.
      - path: ./.env
        required: true
      - path: ./dev.env
        required: true
    environment:
      # Runtime environment variables.
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_LANG: ${NEXT_PUBLIC_LANG}
      NEXT_STRAPI_FE_APIKEY: ${NEXT_STRAPI_FE_APIKEY}
      NEXT_STRAPI_BE_APIKEY: ${NEXT_STRAPI_BE_APIKEY}
      WATCHPACK_POLLING: true # Enable hot reloading for NextJS.
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - ns_net
    depends_on:
      - ns_postgres_dev
      - ns_strapi_dev

  ns_storybook_dev:
    container_name: ns-storybook-dev
    image: nextstory-storybook-dev:latest
    profiles: [storybook]
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      # Runtime environment variables.
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_LANG: ${NEXT_PUBLIC_LANG}
      WATCHPACK_POLLING: true # Enable hot reloading for NextJS.
    volumes:
      - ./frontend/.storybook:/app/.storybook
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    restart: unless-stopped
    ports:
      - "6006:6006"
    networks:
      - ns_net
    command: ["npm", "run", "storybook", "--", "--ci", "--quiet"]

volumes:
  ns_data_dev:
    name: nextstory-data-dev

networks:
  ns_net:
    name: nextstory-net
    driver: bridge
