version: "3.9"
services:
  ns_postgres_prod:
    container_name: ns-postgres-prod
    image: postgres:12.0-alpine
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ns_data_prod:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - ns_net

  ns_strapi_prod:
    container_name: ns-strapi-prod
    image: nextstory-strapi-prod:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ns_postgres_prod
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ns_uploads_prod:/opt/app/public
    ports:
      - "1337:1337"
    networks:
      - ns_net
    depends_on:
      - ns_postgres_prod

  ns_nextjs_prod:
    container_name: ns-nextjs-prod
    image: nextstory-nextjs-prod:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        # Build time environment variables.
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NEXT_PUBLIC_LANG: ${NEXT_PUBLIC_LANG}
        NEXT_STRAPI_FE_APIKEY: ${NEXT_STRAPI_FE_APIKEY}
        NEXT_STRAPI_BE_APIKEY: ${NEXT_STRAPI_BE_APIKEY}
    env_file: .env
    environment:
      # Runtime environment variables.
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_LANG: ${NEXT_PUBLIC_LANG}
      NEXT_STRAPI_FE_APIKEY: ${NEXT_STRAPI_FE_APIKEY}
      NEXT_STRAPI_BE_APIKEY: ${NEXT_STRAPI_BE_APIKEY}
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - ns_net
    depends_on:
      - ns_postgres_prod
      - ns_strapi_prod

volumes:
  ns_data_prod:
    name: nextstory-data-prod
  ns_uploads_prod:
    name: nextstory-uploads-prod

networks:
  ns_net:
    name: nextstory-net
    driver: bridge
